# LATIHAN MATERI ARRAY

In [18]:

# perkalaian matriks array

import numpy as np
A = np.array([22, 17, 27])
B = np.array([44, 90, 73])

perkalian = A * B
print("perkalaian matriks array:")
print(perkalian)

perkalaian matriks array:
[ 968 1530 1971]


In [14]:
# pengurangan matriks array

import numpy as np
A = np.array([22, 17, 27])
B = np.array([44, 90, 73])

pengurangan = A - B
print("pengurangan matriks array:")
print(pengurangan)

pengurangan matriks array:
[-22 -73 -46]


In [15]:
# transpose matriks array

import numpy as np

A = np.array([[22, 17,27,], [44, 90, 73]])

transpose_A = np.transpose(A)
print("transpose matriks array:")
print(transpose_A)

transpose matriks array:
[[22 44]
 [17 90]
 [27 73]]


In [16]:
# Nilai Invers array

import numpy as np

A = np.array([[22, 17],[90, 73]])

invers_A = np.linalg.inv(A)
print("\nInvers matriks A:")
print(invers_A)


Invers matriks A:
[[ 0.96052632 -0.22368421]
 [-1.18421053  0.28947368]]


In [17]:
# determinan dan invers matriks array

import numpy as np

A = np.array([[22, 17],[90, 73]])

determinant_A = np.linalg.det(A)
print("Determinan dari matriks A:", determinant_A)

Determinan dari matriks A: 75.99999999999993
