In [4]:
# perkalian matriks array

import numpy as np

A = np.array([[0,8],[3,1],[6,7]])
B = np.array([[4,4],[9,0],[7,3]])

perkalian = A * B
print(perkalian)

[[ 0 32]
 [27  0]
 [42 21]]


In [5]:
# pengurangan matriks array

import numpy as np

A = np.array([[0,8],[3,1],[6,7]])
B = np.array([[4,4],[9,0],[7,3]])

pengurangan = A - B
print(pengurangan)

[[-4  4]
 [-6  1]
 [-1  4]]


In [6]:
# transpose matriks array

import numpy as np 
A = np.array([[4,4],[9,0],[7,3]])

transpose_A = np.transpose(A)
print(transpose_A)

[[4 9 7]
 [4 0 3]]


In [7]:
# invers matriks array

import numpy as np

A = np.array([[4,4],[9,0]])

invers_A = np.linalg.inv(A)
print("\ninvers matriks A:")
print("invers dari matriks A:", invers_A)


invers matriks A:
invers dari matriks A: [[ 0.          0.11111111]
 [ 0.25       -0.11111111]]


In [9]:
# determinan matriks array

import numpy as np
A = np.array([[4,4],[9,0]])

determinant_A = np.linalg.det(A)
print("determinan dari matriks A:", determinant_A)

determinan dari matriks A: -36.0
